name: op2s_env
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2019.5.15=1
  - certifi=2019.6.16=py37_1
  - cffi=1.12.3=py37h2e261b9_0
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py37_0
  - dbus=1.13.6=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - ignite=0.2.0=py37_0
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py37he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.1.1=py37h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.0.2=py37h7b6447c_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.16.4=py37h7e9f1db_0
  - numpy-base=1.16.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1d=h7b6447c_1
  - pandas=0.25.1=py37he6710b0_0
  - patsy=0.5.1=py37_0
  - pcre=8.43=he6710b0_0
  - pillow=6.1.0=py37h34e0f95_0
  - pip=19.2.2=py37_0
  - pycparser=2.19=py37_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.0=py37_0
  - pytorch=1.2.0=py3.7_cuda10.0.130_cudnn7.6.2_0
  - pytz=2019.2=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scipy=1.3.1=py37h7c811a0_0
  - seaborn=0.9.0=py37_0
  - setuptools=41.0.1=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.29.0=h7b6447c_0
  - statsmodels=0.10.1=py37hdd07704_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.4.0=py37_cu100
  - tornado=6.0.3=py37h7b6447c_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - attrs==19.1.0
    - backcall==0.1.0
    - bleach==3.1.0
    - chardet==3.0.4
    - decorator==4.4.0
    - defusedxml==0.6.0
    - entrypoints==0.3
    - idna==2.8
    - ipykernel==5.1.2
    - ipython==7.7.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.15.1
    - jinja2==2.10.1
    - jsonpatch==1.24
    - jsonpointer==2.0
    - jsonschema==3.0.2
    - jupyter==1.0.0
    - jupyter-client==5.3.1
    - jupyter-console==6.0.0
    - jupyter-core==4.5.0
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbconvert==5.6.0
    - nbformat==4.4.0
    - notebook==6.0.1
    - pandocfilters==1.4.2
    - parso==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.9
    - ptyprocess==0.6.0
    - pygments==2.4.2
    - pyrsistent==0.15.4
    - pyzmq==18.1.0
    - qtconsole==4.5.4
    - requests==2.22.0
    - send2trash==1.5.0
    - terminado==0.8.2
    - testpath==0.4.2
    - torchfile==0.1.0
    - torchnet==0.0.4
    - tqdm==4.35.0
    - traitlets==4.3.2
    - urllib3==1.25.4
    - visdom==0.1.8.9
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - websocket-client==0.56.0
    - widgetsnbextension==3.5.1
    - wrapt==1.11.2

